import 'package:equatable/equatable.dart';

/// Domain model representing a landmark.
///
/// This is a **domain model** - it represents business data in its purest form,
/// independent of any data source (API, database, etc.).
///
/// ## Why separate domain models from data layer models?
///
/// - **LandmarkDTO** (network): Matches the API JSON structure, has `fromJson`/`toJson`
/// - **LandmarkLocal** (database): Matches the SQLite table schema, generated by Drift
/// - **Landmark** (domain): Clean model used by Repository → ViewModel → View
///
/// ## Benefits of separation:
/// - **Decoupling**: UI doesn't depend on API/database structure
/// - **Flexibility**: API or database schema can change without affecting UI
/// - **Testability**: Easy to create test data without mocking data sources
/// - **Clean code**: No serialization logic polluting business models
///
/// ## Data flow:
/// ```
/// Network (JSON) → LandmarkDTO → Repository → Landmark → ViewModel → View
/// Database (SQL) → LandmarkLocal → Repository → Landmark → ViewModel → View
/// ```
class Landmark extends Equatable {
  const Landmark({
    required this.id,
    required this.name,
    required this.description,
    required this.imageUrl,
  });

  final String id;
  final String name;
  final String description;
  final String imageUrl;

  @override
  List<Object?> get props => [id, name, description, imageUrl];
}
